lethalco/lethalco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('protect.urls')),
    path('posts/', include('newsline.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

lethalco/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView


urlpatterns = [
    path('login/', 
         LoginView.as_view(template_name = 'sign/login.html'), 
         name='login'),
    path('logout/', 
         LogoutView.as_view(template_name = 'sign/logout.html'), 
         name='logout'),
    path('signup/', 
         BaseRegisterView.as_view(template_name = 'sign/signup.html'), 
         name='signup'),
]

lethalco/newsline/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    title = models.CharField(max_length = 30)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date = models.DateTimeField(auto_now_add = True)
    text = RichTextUploadingField(null=True)

    meme = 'ME'
    found = 'FO'
    types = [
        (meme, 'Мемы'),
        (found, 'Поиск команды')
    ]
    type = models.CharField(max_length = 13, choices = types, null = True)

    runner = 'R'
    monitor = 'M'
    pclasses = [
        (runner, 'Бегун'),
        (monitor, 'Мониторщик')
    ]
    pclass = models.CharField(max_length = 10, choices = pclasses)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Message(models.Model):
    text = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    sender = models.ForeignKey(User, on_delete = models.CASCADE)
    to = models.IntegerField()
    accept = models.BooleanField(null = True, default = False)

lethalco/templates/post/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}


{% block title %}
Post
{% endblock title %}

{% block content %}

<a href="/posts/">Вернуться ко всем постам</a>
<h1>
    <div class="enjoy-css">
        <h1>{{ post.title }}</h1>
        <hr>
        <h1>{{ post.text|safe }}</h1>
        {{ form.media }}
        <h1><a href="{% url 'profile' post.user_id %}">Автор: {{ post.user.username }}</a></h1>
        <h1>Дата публикации: {{ post.date }}</h1>
        <h1>Тип: {{ post.get_type_display }}</h1>
        <h1>Класс: {{ post.get_pclass_display }}</h1>
        {% if post.type == 'FO' %}
        <h1><a href="{% url 'message' post.user_id%}">Откликнуться</a></h1>
        {% endif %}
        {% if post.user_id == user.id%}
        <h1><a href="{% url 'edit' post.id%}">Обновить</a></h1>
        <h1><a href="{% url 'delete' post.id%}">Удалить</a></h1>
        {% endif %}
    </div>
    

</h1>

{% endblock content %}

lethalco/templates/post/post_create.html
{% extends 'main.html' %}

{% block content %}
<a href="/posts/">Вернуться ко всем постам</a>
<h1>Создать пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

lethalco/templates/post/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем {{ post.title }}?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

lethalco/templates/post/posts.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %} 
{% load custom_filters %}
{% load custom_tags %}
{% load tz %}
{% block title %}
Posts
{% endblock title %}
 
<!-- В контенте на странице мы выводим все посты -->

{% block content %}
    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>
 
    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->
 
    {% for model in models %}
    <div class="model-class">
        {{ model.name }} 
    </div>
    {% endfor %}
   <hr>
   {% if posts %}
       <table>
            <tr class="{% cycle 'blue' 'white' %}">
               <td>Заголовок</td>
               <td>Дата</td>
               <td>Текст</td>
               <td>Тип</td>
               <td>Класс</td>

           </tr>
           

           {% for post in posts %}
           <tr class="{% cycle 'blue' 'white' %}">
               <td><a href="/posts/{{ post.id }}"> {{ post.title|censor }}</a></td>
               <td>{{ post.time|date:'d M Y' }}</td>
               <td>{{ post.text|censor|truncatewords:20 }}</td>
               <td>{{ post.type }}</td>
               <td>{{ post.pclass }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}


   {% if page_obj.has_previous %}
   {# Для каждой ссылки пагинации указываем обработку через новый тег #}
   <a href="?{% url_replace page=1 %}">1</a>
   {% if page_obj.previous_page_number != 1 %}
       ...
       <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
   {% endif %}
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
   <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
   {% if paginator.num_pages != page_obj.next_page_number %}
       ...
       <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
   {% endif %}
{% endif %}

{% endblock content %}